# -*- coding: utf-8 -*-
"""Actividad Semana 12: Consenso Distribuido – Paxos y Raft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2oWopYmZvWoVClkfwWp8H6eKoJ3evzw
"""

import time
import random
import threading

class Node:
    def __init__(self, node_id, all_nodes):
        self.node_id = node_id
        self.all_nodes = all_nodes  # Referencia a los demás nodos simulados
        self.state = "Follower"
        self.current_term = 0
        self.voted_for = None
        self.log = []  # Lista de diccionarios: {'term': int, 'command': str}
        self.is_alive = True

        # Tiempos de timeout aleatorios para evitar colisiones crónicas
        self.election_timeout = random.uniform(1.5, 3.0)
        self.last_heartbeat_time = time.time()

        # Hilo de ejecución del nodo
        self.thread = threading.Thread(target=self.run, daemon=True)
        self.thread.start()

    def log_msg(self, message):
        print(f"[Nodo {self.node_id} - {self.state} - Term {self.current_term}]: {message}")

    def run(self):
        while True:
            if not self.is_alive:
                time.sleep(0.5)
                continue

            if self.state == "Follower":
                # Si pasa el tiempo de timeout sin recibir latido, se vuelve candidato
                if time.time() - self.last_heartbeat_time > self.election_timeout:
                    self.log_msg("Timeout de latido expirado. Iniciando elección...")
                    self.start_election()

            elif self.state == "Leader":
                # El líder envía latidos constantemente a los nodos vivos
                self.send_heartbeats()
                time.sleep(0.5)

            time.sleep(0.1)

    def start_election(self):
        self.state = "Candidate"
        self.current_term += 1
        self.voted_for = self.node_id
        votes = 1
        self.log_msg("Postulándose como candidato.")

        for target_id, node in self.all_nodes.items():
            if target_id == self.node_id:
                continue
            # Solicitar voto
            if node.is_alive and node.receive_request_vote(self.node_id, self.current_term):
                votes += 1

        # Verificar si obtuvo mayoría (en 3 nodos, la mayoría es 2)
        if votes >= 2:
            self.state = "Leader"
            self.log_msg("¡Elegido como nuevo LÍDER del clúster!")
        else:
            self.log_msg("No obtuvo mayoría de votos. Volviendo a Follower.")
            self.state = "Follower"
            self.last_heartbeat_time = time.time()

    def receive_request_vote(self, candidate_id, term):
        if not self.is_alive: return False

        if term > self.current_term:
            self.current_term = term
            self.voted_for = None
            self.state = "Follower"

        if (self.voted_for is None or self.voted_for == candidate_id) and term >= self.current_term:
            self.voted_for = candidate_id
            self.last_heartbeat_time = time.time()
            self.log_msg(f"Voto otorgado al Candidato {candidate_id}")
            return True
        return False

    def send_heartbeats(self):
        for target_id, node in self.all_nodes.items():
            if target_id == self.node_id:
                continue
            if node.is_alive:
                node.receive_heartbeat(self.node_id, self.current_term, self.log)

    def receive_heartbeat(self, leader_id, term, leader_log):
        if not self.is_alive: return

        if term >= self.current_term:
            self.current_term = term
            self.state = "Follower"
            self.last_heartbeat_time = time.time()

            # Replicar Log si el líder tiene datos nuevos
            if len(leader_log) > len(self.log):
                self.log = list(leader_log)
                self.log_msg(f"Log sincronizado con el Líder {leader_id}. Estado actual: {self.log}")

    def propose_value(self, command):
        if self.state != "Leader":
            self.log_msg("ERROR: No soy el líder. No puedo procesar propuestas.")
            return False

        self.log_msg(f"Propuesta recibida del cliente: '{command}'. Replicando...")
        self.log.append({'term': self.current_term, 'command': command})

        # Contar cuántos nodos logran replicar
        success_count = 1
        for target_id, node in self.all_nodes.items():
            if target_id == self.node_id: continue
            if node.is_alive:
                node.receive_heartbeat(self.node_id, self.current_term, self.log)
                success_count += 1

        if success_count >= 2:
            self.log_msg(f"Consenso logrado para '{command}' (Mayoría alcanzada: {success_count}/3).")
            return True
        else:
            self.log_msg(f"Fallo de consenso para '{command}'. Sin mayoría.")
            return False

# --- SIMULACIÓN DEL ENTORNO ---
if __name__ == "__main__":
    cluster = {}
    # Inicializar 3 nodos
    for i in range(1, 4):
        cluster[i] = Node(node_id=i, all_nodes=cluster)

    time.sleep(3) # Esperar a que ocurra la primera elección de líder

    # Encontrar quién es el líder actual
    leader_node = None
    for n in cluster.values():
        if n.state == "Leader":
            leader_node = n
            break

    # 1. Proponer un valor inicial exitoso
    if leader_node:
        leader_node.propose_value("A=1")

    time.sleep(2)
    print("\n--- SIMULANDO FALLO: Tumbando al líder actual ---")
    old_leader_id = leader_node.node_id
    cluster[old_leader_id].is_alive = False
    cluster[old_leader_id].state = "Follower"
    print(f"-> El Nodo {old_leader_id} (Líder) ha dejado de responder por completo.\n")

    # Esperar a que los followers noten la ausencia y elijan un nuevo líder
    time.sleep(4)

    # Buscar el nuevo líder
    new_leader = None
    for n in cluster.values():
        if n.state == "Leader":
            new_leader = n
            break

    # 2. Proponer un nuevo valor con el nuevo líder para validar resiliencia
    if new_leader:
        print(f"\n--- ENVIANDO PROPUESTA AL NUEVO LÍDER (Nodo {new_leader.node_id}) ---")
        new_leader.propose_value("A=2")
    else:
        print("No se pudo consolidar un nuevo líder a tiempo.")

    time.sleep(2)
    print("\nSimulación finalizada con éxito.")